## Global Variables
@BaseUrl = http://localhost:8080/api

@authToken = Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJiMjBkZjY5Ny04MGU3LTQ2ZmUtYTAxMC01ZGY3MjQ5ZWIwZDAiLCJpYXQiOjE3NjM4MjM3NDYsImV4cCI6MTc2MzgzMDk0Nn0.tRAlm6Kcbn_KVparQ31dWJJm2ceyst1jP0-VHsJy7F7WE4Rg1qh9rt9fIwCpz3Kl

## Cash Flow
## ---------------------------------
# @name PostCashFlow
POST {{BaseUrl}}/cash-flows
Content-Type: application/json
Authorization: {{authToken}}

{
    "type": "Outflow",
    "source": "Tabungan Pribadi",
    "label": "alat-elektronik",
    "amount": 10000,
    "description": "Kebutuhan komputer server"
}
###

# Response Example: PostCashFlow
{
    "status": "success",
    "message": "Berhasil menambahkan data",
    "data": {
        "id": "c700f0d8-82bc-4410-af73-68f8f1f247d1"
    }
}
###

# @name GetAllCashFlows
GET {{BaseUrl}}/cash-flows
Authorization: {{authToken}}
###

# @name GetAllCashFlowsWithSearch
GET {{BaseUrl}}/cash-flows?search=Pribadi
Authorization: {{authToken}}
###
# Response Example: GetAllCashFlows && GetAllCashFlowsWithSearch
{
    "status": "success",
    "message": "Berhasil mengambil data",
    "data": {
        "cash_flows": [
            {
                "id": "c700f0d8-82bc-4410-af73-68f8f1f247d1",
                "type": "Inflow",
                "source": "Gaji",
                "label": "gaji-bulanan",
                "amount": 400000,
                "description": "Menerima gaji bulanan dari perusahaan.",
                "createdAt": "2025-11-05T03:24:31.134753",
                "updatedAt": "2025-11-05T03:24:31.134753"
            },
            {
                "id": "c700f0d8-82bc-4410-af73-68f8f1f247d2",
                "type": "Outflow",
                "source": "cash",
                "label": "alat-mandi",
                "amount": 100000,
                "description": "Membeli kebutuhan alat mandi seperti sabun, odol.",
                "createdAt": "2025-11-05T03:24:31.134753",
                "updatedAt": "2025-11-05T03:24:31.134753"
            },
        ]
    }
}
###

@cashFlowId = {{GetAllCashFlows.response.body.data.cashFLows[0].id}}

# @name GetCashFlowById
GET {{BaseUrl}}/cash-flows/{{cashFlowId}}
Authorization: {{authToken}}
###

# Response Example: GetCashFlowById
{
    "status": "success",
    "message": "Berhasil mengambil data",
    "data": {
        "cash_flow": {
            "id": "c700f0d8-82bc-4410-af73-68f8f1f247d1",
            "type": "Inflow",
            "source": "Gaji",
            "label": "gaji-bulanan",
            "amount": 400000,
            "description": "Menerima gaji bulanan dari perusahaan.",
            "createdAt": "2025-11-05T03:24:31.134753",
            "updatedAt": "2025-11-05T03:24:31.134753"
        }
    }
}

###

# @name GetCashFlowLabels
GET {{BaseUrl}}/cash-flows/labels
Authorization: {{authToken}}
###

# Response Example: GetCashFlowLabels
{
    "status": "success",
    "message": "Berhasil mengambil data",
    "data": {
        "labels": [
            "gaji-bulanan",
            "alat-mandi",
            "alat-elektronik"
        ]
    }
}
###

# @name PutCashFlowById
PUT {{BaseUrl}}/cash-flows/{{cashFlowId}}
Content-Type: application/json
Authorization: {{authToken}}

{
    "type": "Inflow",
    "source": "Freelance Project",
    "label": "proyek-freelance",
    "amount": 5000000,
    "description": "Pendapatan dari proyek freelance pengembangan web."
}
###

# Response Example: PutCashFlowById
{
    "status": "success",
    "message": "Berhasil memperbarui data"
}
###

# @name DeleteCashFlowById
DELETE {{BaseUrl}}/cash-flows/{{cashFlowId}}
Authorization: {{authToken}}
###

# Response Example: DeleteCashFlowById
{
    "status": "success",
    "message": "Berhasil menghapus data"
}
###